export const questionData = [
  {
    category: "Allgemeine Wissenschaft",
    id: "7392058164",
    correctAnswer: "Sauerstoff",
    incorrectAnswers: ["Eisen", "Gold", "Stickstoff"],
    question: 'Welches Element hat die chemische Abkürzung "O"?',
  },

  {
    category: "Geographie",
    id: "4827365910",
    correctAnswer: "Canbarra",
    incorrectAnswers: ["Sydney", "Melbourne", "Brisbane"],
    question: "Was ist die Hauptstadt von Australien?",
  },

  {
    category: "Film und Fernsehen",
    id: "9051732846",
    correctAnswer: "Emma Stone",
    incorrectAnswers: ["Emma Watson", "Natalie Portman", "Meryl Streep"],
    question:
      'Wer hat den Oscar für die beste weibliche Hauptrolle im Film "La La Land" gewonnen?',
  },
  {
    category: "Geschichte",
    id: "6278943105",
    correctAnswer: "1918",
    incorrectAnswers: ["1916", "1920", "1939"],
    question: "In welchem Jahr endete der erste Weltkrieg?",
  },

  {
    category: "Musik",
    id: "1492086375",
    correctAnswer: "Flöte",
    incorrectAnswers: ["Geige", "Klavier", "Trompete"],
    question:
      'Welches Instrument spielt der Protagonist in Mozart\'s "Die Zauberflöte"?',
  },
  {
    category: "Sport",
    id: "3442286875",
    correctAnswer: "Miroslav Klose",
    incorrectAnswers: ["Cristiano Ronaldo", "Lionel Messi", "Neymar"],
    question:
      "Welcher Fußballspieler hält den Rekord für die meisten Tore in der Geschichte der FIFA-Weltmeisterschaft?",
  },
  {
    category: "Literatur",
    id: "8839148367",
    correctAnswer: "Franz Kafka",
    incorrectAnswers: ["Fyodor Dostoevsky", " George Orwell", "Virginia Woolf"],
    question: 'Wer ist der Autor des Romans "Die Verwandlung"?',
  },
  {
    category: "Naturwissenschaften",
    id: "1379526437",
    correctAnswer: "Helium",
    incorrectAnswers: ["Sauerstoff", "Natrium", "Eisen"],
    question: "Welches der folgenden Elemente ist ein Edelgas?",
  },
  {
    category: "Popkultur",
    id: "2998624777",
    correctAnswer: "Superman",
    incorrectAnswers: ["Spider-Man", "Iron Man", "Batman"],
    question: 'Welcher Superheld trägt den Spitznamen "Der Mann aus Stahl"?',
  },
  {
    category: "Geschichte",
    id: "3782256487",
    correctAnswer: "George Washington",
    incorrectAnswers: ["John Adams", "Thomas Jefferson", "Abraham Lincoln"],
    question: "Wer war der erste Präsident der Vereinigten Staaten?",
  },
  {
    category: "Musik",
    id: "7688265481",
    correctAnswer: "Queen",
    incorrectAnswers: ["The Rolling Stones", "The Beatles", "Led Zeppelin"],
    question:
      'Welche Band ist für Hits wie "Bohemian Rhapsody" und "We Will Rock You" bekannt?',
  },
  {
    category: "Geographie",
    id: "8625488961",
    correctAnswer: "Nil",
    incorrectAnswers: ["Amazonas", "Mississippi", "Jangtse"],
    question: "Welcher Fluss ist der längste der Welt?",
  },
  {
    category: "Wissenschaft",
    id: "4445763338",
    correctAnswer: "Volt",
    incorrectAnswers: ["Watt", "Ampere", "Ohm"],
    question:
      "Welche Einheit wird für die Messung der elektrischen Spannung verwendet?",
  },
  {
    category: "Film und Fernsehen",
    id: "4445763338",
    correctAnswer: "Tom Hanks",
    incorrectAnswers: ["Leonardo DiCaprio", "Brad Pitt", "Johnny Depp"],
    question: 'Wer spielte die Hauptrolle in "Forrest Gump?"',
  },
  {
    category: "Sprache",
    id: "3839264717",
    correctAnswer: "Chinesisch",
    incorrectAnswers: ["Deutsch", "Russisch", "Arabisch"],
    question:
      "Welche der folgenden Sprachen verwendet nicht das lateinische Alphabet?",
  },
  {
    category: "Sport",
    id: "2258478996",
    correctAnswer: "Brasilien",
    incorrectAnswers: ["China", "Russland", "Kanada"],
    question: "In welchem Land fand die Olympiade 2016 statt?",
  },
  {
    category: "Technologie",
    id: "1745896522",
    correctAnswer: "Google",
    incorrectAnswers: ["Apple", "Microsoft", "Samsung"],
    question: "Welches Unternehmen entwickelte das Betriebssystem Android?",
  },
  {
    category: "Naturwissenschaften",
    id: "5454698552",
    correctAnswer: "Stickstoff",
    incorrectAnswers: ["Sauerstoff", "Kohlendioxid", "Wasserstoff"],
    question: "Welches Gas macht den größten Teil der Erdatmosphäre aus?",
  },
  {
    category: "Wissenschaft",
    id: "3567348552",
    correctAnswer: "Proton",
    incorrectAnswers: ["Elektron", "Neutron", "Quark"],
    question: "Was ist ein positiv geladenes Teilchen im Atomkern?",
  },
  {
    category: "Geographie",
    id: "6545682590",
    correctAnswer: "Mount Everest",
    incorrectAnswers: ["K2", "Makalu", "Lhotse"],
    question: "Welcher Berg ist der höchste der Welt?",
  },
  {
    category: "Literatur",
    id: "7654325678",
    correctAnswer: "F. Scott Fitzgerald",
    incorrectAnswers: ["Ernest Hemingway", "J.D. Salinger", "Virginia Woolf"],
    question: "Wer schrieb 'The Great Gatsby'?",
  },
  {
    category: "Sport",
    id: "6788863807",
    correctAnswer: "Usain Bolt",
    incorrectAnswers: ["Michael Phelps", "Serena Williams", "Lionel Messi"],
    question: "Wer hält den Weltrekord im 100-Meter-Lauf?",
  },
  {
    category: "Film",
    id: "3567899997",
    correctAnswer: "Quentin Tarantino",
    incorrectAnswers: [
      "Christopher Nolan",
      "Steven Spielberg",
      "Martin Scorsese",
    ],
    question: "Wer inszenierte 'Pulp Fiction'?",
  },
  {
    category: "Geschichte",
    id: "3575838676",
    correctAnswer: "Kalter Krieg",
    incorrectAnswers: ["Erster Weltkrieg", "Zweiter Weltkrieg", "Vietnamkrieg"],
    question: "Welche Periode folgte unmittelbar nach dem Zweiten Weltkrieg?",
  },
  {
    category: "Wissenschaft",
    id: "9789657857",
    correctAnswer: "Photosynthese",
    incorrectAnswers: ["Zellatmung", "Fermentation", "Osmose"],
    question:
      "Wie nennt man den Prozess, bei dem Pflanzen Licht in Energie umwandeln?",
  },
  {
    category: "Geographie",
    id: "8932464598",
    correctAnswer: "Nil",
    incorrectAnswers: ["Amazonas", "Jangtsekiang", "Mekong"],
    question: "Welcher Fluss ist der längste der Welt?",
  },
  {
    category: "Literatur",
    id: "34457282906",
    correctAnswer: "Gabriel Garcia Marquez",
    incorrectAnswers: ["Isabel Allende", "Julio Cortázar", "Pablo Neruda"],
    question: "Wer schrieb 'Hundert Jahre Einsamkeit'?",
  },
  {
    category: "Sport",
    id: "2948753453",
    correctAnswer: "Neymar",
    incorrectAnswers: ["Cristiano Ronaldo", "Lionel Messi", "Kylian Mbappé"],
    question:
      "Wer ist ein brasilianischer Fußballspieler, der für Paris Saint-Germain spielt?",
  },
  {
    category: "Film",
    id: "0239453534",
    correctAnswer: "The Shawshank Redemption",
    incorrectAnswers: ["The Godfather", "Pulp Fiction", "Inception"],
    question:
      "Welcher Film wird oft als einer der besten aller Zeiten bezeichnet?",
  },
  {
    category: "Geschichte",
    id: "7574564777",
    correctAnswer: "Mao Zedong",
    incorrectAnswers: ["Chiang Kai-shek", "Sun Yat-sen", "Deng Xiaoping"],
    question: "Wer war der Gründer der Volksrepublik China?",
  },
  {
    category: "Wissenschaft",
    id: "3456257567",
    correctAnswer: "Albert Einstein",
    incorrectAnswers: ["Isaac Newton", "Galileo Galilei", "Niels Bohr"],
    question: "Wer formulierte die Relativitätstheorie?",
  },
  {
    category: "Geographie",
    id: "2756557435",
    correctAnswer: "Sydney",
    incorrectAnswers: ["Melbourne", "Brisbane", "Perth"],
    question:
      "Welche Stadt ist die Hauptstadt von New South Wales, Australien?",
  },
  {
    category: "Literatur",
    id: "7593826587",
    correctAnswer: "Harper Lee",
    incorrectAnswers: ["J.K. Rowling", "George Orwell", "F. Scott Fitzgerald"],
    question: "Wer schrieb 'To Kill a Mockingbird'?",
  },
  {
    category: "Sport",
    id: "2749234244",
    correctAnswer: "Michael Jordan",
    incorrectAnswers: ["LeBron James", "Kobe Bryant", "Magic Johnson"],
    question:
      "Wer wird oft als der beste Basketballspieler aller Zeiten betrachtet?",
  },
  {
    category: "Film",
    id: "7744920576",
    correctAnswer: "The Matrix",
    incorrectAnswers: [
      "Blade Runner",
      "Inception",
      "Eternal Sunshine of the Spotless Mind",
    ],
    question: "Welcher Film prägte den Begriff 'Bullet Time'?",
  },
  {
    category: "Geschichte",
    id: "6483776017",
    correctAnswer: "Napoleon Bonaparte",
    incorrectAnswers: [
      "Alexander der Große",
      "Julius Caesar",
      "Kaiser Wilhelm I",
    ],
    question:
      "Wer war der Herrscher über Frankreich während der napoleonischen Ära?",
  },
  {
    category: "Wissenschaft",
    id: "9305826500",
    correctAnswer: "Euklid",
    incorrectAnswers: ["Pythagoras", "Archimedes", "Aristoteles"],
    question: "Wer wird als 'Vater der Geometrie' bezeichnet?",
  },
  {
    category: "Geographie",
    id: "5454248752",
    correctAnswer: "Tokio",
    incorrectAnswers: ["Peking", "Seoul", "Shanghai"],
    question: "Welche Stadt ist die bevölkerungsreichste Metropole der Welt?",
  },
  // difficult
  {
    category: "Wissenschaft",
    id: "21",
    correctAnswer: "Higgs-Boson",
    incorrectAnswers: ["Quark-Gluon-Plasma", "Graviton", "Neutrino"],
    question: "Welches Elementarteilchen wurde 2012 am CERN entdeckt?",
  },
  {
    category: "Geographie",
    id: "22",
    correctAnswer: "McMurdo-Station",
    incorrectAnswers: [
      "Amundsen-Scott-Südpolstation",
      "Halley-Forschungsstation",
      "Palmer-Station",
    ],
    question: "Welche Forschungsstation ist die größte in der Antarktis?",
  },
  {
    category: "Literatur",
    id: "23",
    correctAnswer: "Fyodor Dostoevsky",
    incorrectAnswers: ["Leo Tolstoy", "Anton Chekhov", "Ivan Turgenev"],
    question: "Wer schrieb 'Die Brüder Karamasow'?",
  },
  {
    category: "Sport",
    id: "24",
    correctAnswer: "Ayrton Senna",
    incorrectAnswers: ["Alain Prost", "Michael Schumacher", "Niki Lauda"],
    question: "Welcher Formel-1-Fahrer starb 1994 bei einem Rennen in Imola?",
  },
  {
    category: "Film",
    id: "25",
    correctAnswer: "Akira Kurosawa",
    incorrectAnswers: ["Ingmar Bergman", "Federico Fellini", "Stanley Kubrick"],
    question: "Welcher Regisseur schuf den Film 'Die sieben Samurai'?",
  },
  {
    category: "Geschichte",
    id: "26",
    correctAnswer: "Babylonischer Talmud",
    incorrectAnswers: ["Mishnah", "Jerusalemer Talmud", "Midrasch"],
    question: "Welches jüdische Schriftwerk ist die Grundlage des Talmuds?",
  },
  {
    category: "Wissenschaft",
    id: "27",
    correctAnswer: "Heisenberg",
    incorrectAnswers: ["Schroedinger", "Bohr", "Einstein"],
    question:
      "Wer formulierte das Unsicherheitsprinzip in der Quantenmechanik?",
  },
  {
    category: "Geographie",
    id: "28",
    correctAnswer: "Andorra",
    incorrectAnswers: ["Liechtenstein", "San Marino", "Monaco"],
    question: "Welches europäische Land hat keinen Flughafen?",
  },
  {
    category: "Literatur",
    id: "29",
    correctAnswer: "Italo Calvino",
    incorrectAnswers: [
      "Gabriel Garcia Marquez",
      "Haruki Murakami",
      "Jorge Luis Borges",
    ],
    question: "Wer schrieb 'Wenn ein Reisender in einer Winternacht'?",
  },
  {
    category: "Sport",
    id: "30",
    correctAnswer: "Bobby Fischer",
    incorrectAnswers: ["Garry Kasparov", "Anatoly Karpov", "Mikhail Tal"],
    question: "Wer war der Schachweltmeister im Jahr 1972?",
  },
  {
    category: "Film",
    id: "31",
    correctAnswer: "Terrence Malick",
    incorrectAnswers: [
      "David Lynch",
      "Paul Thomas Anderson",
      "Quentin Tarantino",
    ],
    question: "Wer führte Regie bei 'The Thin Red Line'?",
  },
  {
    category: "Geschichte",
    id: "32",
    correctAnswer: "Bundesverfassungsgericht",
    incorrectAnswers: [
      "Reichsgericht",
      "Volksgerichtshof",
      "Oberstes Gerichtshof",
    ],
    question:
      "Welches Gericht ist das höchste Verfassungsorgan der Bundesrepublik Deutschland?",
  },
  {
    category: "Wissenschaft",
    id: "33",
    correctAnswer: "Max Planck",
    incorrectAnswers: ["Erwin Schrödinger", "Niels Bohr", "Werner Heisenberg"],
    question: "Wer formulierte das Plancksche Wirkungsquantum?",
  },
  {
    category: "Geographie",
    id: "34",
    correctAnswer: "Murmansk",
    incorrectAnswers: ["Arkhangelsk", "Vladivostok", "Kaliningrad"],
    question: "Welche russische Stadt liegt am weitesten nördlich?",
  },
  {
    category: "Literatur",
    id: "35",
    correctAnswer: "Salman Rushdie",
    incorrectAnswers: ["Arundhati Roy", "Orhan Pamuk", "Kazuo Ishiguro"],
    question: "Wer wurde für 'Die satanischen Verse' mit einer Fatwa belegt?",
  },
  {
    category: "Sport",
    id: "36",
    correctAnswer: "Sergei Bubka",
    incorrectAnswers: ["Renaud Lavillenie", "Yelena Isinbayeva", "Pole Vault"],
    question: "Wer hält den Weltrekord im Stabhochsprung?",
  },
  {
    category: "Film",
    id: "37",
    correctAnswer: "A Clockwork Orange",
    incorrectAnswers: [
      "Blade Runner",
      "2001: A Space Odyssey",
      "Full Metal Jacket",
    ],
    question: "Welcher Film basiert auf einem Roman von Anthony Burgess?",
  },
  {
    category: "Geschichte",
    id: "38",
    correctAnswer: "Karl der Große",
    incorrectAnswers: ["Augustus", "Napoleon Bonaparte", "Peter der Große"],
    question: "Wer war der erste Kaiser des Heiligen Römischen Reiches?",
  },
  {
    category: "Wissenschaft",
    id: "39",
    correctAnswer: "Lise Meitner",
    incorrectAnswers: [
      "Marie Curie",
      "Rosalind Franklin",
      "Dorothy Crowfoot Hodgkin",
    ],
    question: "Wer entdeckte das Element Protactinium?",
  },
  {
    category: "Geographie",
    id: "40",
    correctAnswer: "Lake Baikal",
    incorrectAnswers: ["Caspian Sea", "Superior Lake", "Victoria Lake"],
    question: "Welcher See hat das größte Volumen aller Seen der Welt?",
  },
];
